-- Function to allow a user to delete their own account
-- This must be SECURITY DEFINER to access auth.users
CREATE OR REPLACE FUNCTION delete_own_account()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  DELETE FROM auth.users WHERE id = auth.uid();
END;
$$;

-- Function to wipe user content (keeping account and profile/mask active)
-- or maybe we want to keep the profile but empty it?
-- The spec says "Le compte reste actif, mais le profil est vidé" (Profile emptied? Or just content?)
-- "Supprimer toutes les confessions et commentaires" -> Content.
CREATE OR REPLACE FUNCTION wipe_user_content()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Delete all content created by the user
  DELETE FROM public.confessions WHERE user_id = auth.uid();
  DELETE FROM public.comments WHERE user_id = auth.uid();
  
  -- Also remove interactions
  DELETE FROM public.likes WHERE user_id = auth.uid();
  DELETE FROM public.validations WHERE user_id = auth.uid();
  DELETE FROM public.veilles WHERE user_id = auth.uid();
  
  -- Notifications generated by this user will be deleted via cascade if related_id is deleted,
  -- but we can also clean up notifications acting as sender (if we had a sender_id, but notification logic is different)
  -- Simply deleting primary content is usually enough for "Wipe Content".
END;
$$;
